Repository PrestaShop/prestashop-flashlight, pull requests merged in 2024-02, with the labels that each got.

#57 feat(php): Php config
  assets/php-configuration.sh
  docker/alpine.Dockerfile
  docker/debian.Dockerfile
Labels: ready to review

#73 docs: Some spell checks
  README.md
  examples/auto-install-modules/README.md
  examples/auto-install-modules/init-scripts/install-mock.sh
  examples/basic-example/README.md
  examples/develop-a-module/README.md
  examples/develop-prestashop/README.md
  examples/ngrok-tunnel/README.md
  examples/with-init-scripts/README.md
  examples/with-post-scripts/README.md
Labels: documentation

#76 minor(env): test prestashop-flashlight with the latest release
  .github/workflows/pull-request.yml
Labels: ready to review

#59 feat(build): add PrestaShop nightly support
  .github/workflows/pull-request.yml
  README.md
  build.sh
  docker/alpine.Dockerfile
  docker/debian.Dockerfile
Labels: enhancement, ready to review

#79 chore(ga): define timeouts to avoid 6h timeout
  .github/workflows/docker-publish.yml
  .github/workflows/nightly-cron-publish.yml
  .github/workflows/pull-request.yml
Labels: ready to review
